---
- hosts: grafana_servers
  become: true
  tasks:
    - name: Stop Grafana service
      systemd:
        name: grafana-server
        state: stopped
        enabled: no

    - name: Remove Grafana
      package:
        name: grafana
        state: absent

    - name: Remove Grafana repository file
      file:
        path: /etc/yum.repos.d/grafana.repo
        state: absent

    - name: Remove Grafana data directory
      file:
        path: /var/lib/grafana
        state: absent

